controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_fizzbuzz:
    path: /fizzbuzz
    controller: App\Controller\FizzBuzzController::getFizzBuzz
    methods: GET