controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

fizzbuzz:
    path: /fizzbuzz
    controller: App\Controller\FizzBuzzController::getFizzBuzz
    methods: GET

fizzbuzz_statistics:
    path: /fizzbuzz/statistics
    controller: App\Controller\FizzBuzzStatisticsController::getMostFrequentRequest
    methods: [GET]