monolog:
    channels: ['app', 'request', 'messenger', 'error']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!request", "!messenger", "!error"]
        request:
            type: stream
            path: "%kernel.logs_dir%/request.log"
            level: debug
            channels: ["request"]
        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.log"
            level: debug
            channels: ["messenger"]
        error:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
            channels: ["error"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]